drop table if exists ca.bill;
drop table if exists ca.bill_history;
drop table if exists ca.bill_schedule;
drop table if exists ca.chamber_vote_result;
drop table if exists ca.committee_vote_result;
drop table if exists ca.chamber;
drop table if exists ca.chamber_schedule;
drop table if exists ca.committee;
drop table if exists ca.bill_issue;
drop table if exists ca.issue
